-- MySQL Script generated by MySQL Workbench
-- Wed Feb 13 00:06:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_tramite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_tramite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_tramite` DEFAULT CHARACTER SET utf8 ;
USE `DB_tramite` ;

-- -----------------------------------------------------
-- Table `DB_tramite`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_tramite`.`Persona` (
  `Dni` INT(8) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`Dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_tramite`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_tramite`.`Area` (
  `IdArea` SMALLINT NOT NULL AUTO_INCREMENT,
  `NombreArea` VARCHAR(45) NULL,
  `AbreviaArea` VARCHAR(10) NULL,
  PRIMARY KEY (`IdArea`),
  UNIQUE INDEX `nombre_area_UNIQUE` (`NombreArea` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_tramite`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_tramite`.`Login` (
  `IdLogin` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Dni` INT(8) NOT NULL,
  `IdArea` INT NOT NULL,
  `TipoLogin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdLogin`),
  INDEX `fk_login_persona_idx` (`Dni` ASC) VISIBLE,
  INDEX `fk_login_area1_idx` (`IdArea` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_login_persona`
    FOREIGN KEY (`Dni`)
    REFERENCES `DB_tramite`.`Persona` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_area1`
    FOREIGN KEY (`IdArea`)
    REFERENCES `DB_tramite`.`Area` (`IdArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_tramite`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_tramite`.`TipoDocumento` (
  `IdTipo` SMALLINT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `AbreviaTipo` VARCHAR(45) NULL,
  `IdArea` SMALLINT NOT NULL,
  PRIMARY KEY (`IdTipo`),
  INDEX `fk_tipo_documento_area1_idx` (`IdArea` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_documento_area1`
    FOREIGN KEY (`IdArea`)
    REFERENCES `DB_tramite`.`Area` (`IdArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_tramite`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_tramite`.`Documento` (
  `IdDocumento1` INT NOT NULL AUTO_INCREMENT,
  `CodDocumento` VARCHAR(25) NOT NULL,
  `NombreProce` VARCHAR(100) NULL,
  `Año` SMALLINT NULL,
  `Numero` SMALLINT NULL,
  `IdTipo` SMALLINT NOT NULL,
  `Asunto` VARCHAR(60) NULL,
  `DetalleAsunto` VARCHAR(150) NULL,
  `Folios` SMALLINT NULL,
  `NumArchivador` SMALLINT NULL,
  `Fecha` DATE NULL,
  `IdArea` SMALLINT NOT NULL,
  `Observacion` VARCHAR(250) NULL,
  PRIMARY KEY (`IdDocumento1`),
  INDEX `fk_documento_tipo_documento1_idx` (`IdTipo` ASC) VISIBLE,
  INDEX `fk_documento_area1_idx` (`IdArea` ASC) VISIBLE,
  UNIQUE INDEX `CodDocumento_UNIQUE` (`CodDocumento` ASC) VISIBLE,
  CONSTRAINT `fk_documento_tipo_documento1`
    FOREIGN KEY (`IdTipo`)
    REFERENCES `DB_tramite`.`TipoDocumento` (`IdTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_area1`
    FOREIGN KEY (`IdArea`)
    REFERENCES `DB_tramite`.`Area` (`IdArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_tramite`.`Archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_tramite`.`Archivo` (
  `IdArchivo` INT NOT NULL AUTO_INCREMENT,
  `Archivo` LONGBLOB NOT NULL,
  `IdDocumento` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdArchivo`),
  INDEX `fk_archivo_documento1_idx` (`IdDocumento` ASC) VISIBLE,
  CONSTRAINT `fk_archivo_documento1`
    FOREIGN KEY (`IdDocumento`)
    REFERENCES `DB_tramite`.`Documento` (`CodDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_tramite`.`Tramite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_tramite`.`Tramite` (
  `IdTramite` INT NOT NULL AUTO_INCREMENT,
  `IdDocumento` VARCHAR(45) NOT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  `AreaOrigen` VARCHAR(45) NULL,
  `AreaDestino` VARCHAR(45) NULL,
  `Accion` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Observacion` VARCHAR(150) NULL,
  PRIMARY KEY (`IdTramite`),
  INDEX `fk_tramite_documento1_idx` (`IdDocumento` ASC) VISIBLE,
  CONSTRAINT `fk_tramite_documento1`
    FOREIGN KEY (`IdDocumento`)
    REFERENCES `DB_tramite`.`Documento` (`CodDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
